/**
 * ECO Codes Library
 * 
 * This library provides descriptions for Encyclopedia of Chess Openings (ECO) codes
 * to enhance the user experience in the Chessy application.
 * 
 * Usage:
 * 1. Include this file in your HTML
 * 2. Call getEcoDescription(ecoCode) to get a description for any ECO code
 */

const ecoCodesLibrary = {
    // A-series: Flank Openings
    "A00": "Irregular Openings (including Polish Opening, Sokolsky Opening)",
    "A01": "Nimzovich-Larsen Attack",
    "A02": "Bird's Opening (1.f4)",
    "A03": "Bird's Opening, 1...d5",
    "A04": "Reti Opening",
    "A05": "Reti Opening, King's Indian Attack",
    "A06": "Reti Opening, 1...d5",
    "A07": "Reti Opening, King's Indian Attack (Barcza System)",
    "A08": "Reti Opening, King's Indian Attack",
    "A09": "Reti Opening, Advance Variation",
    "A10": "English Opening",
    "A11": "English Opening, Caro-Kann Defensive System",
    "A12": "English Opening, Caro-Kann Defensive System",
    "A13": "English Opening, Agincourt Defense",
    "A14": "English Opening, Neo-Catalan Declined",
    "A15": "English Opening, Anglo-Indian Defense",
    "A16": "English Opening, Anglo-Indian Defense, Queen's Knight Variation",
    "A17": "English Opening, Anglo-Indian Defense, Queen's Knight Variation",
    "A18": "English Opening, Mikenas-Carls Variation",
    "A19": "English Opening, Mikenas-Carls, Sicilian Variation",
    "A20": "English Opening, King's English Variation",
    "A21": "English Opening, King's English Variation, Reversed Sicilian",
    "A22": "English Opening, King's English, Two Knights' Variation",
    "A23": "English Opening, Bremen System, Keres Variation",
    "A24": "English Opening, Bremen System with 1...g6",
    "A25": "English Opening, Sicilian Reversed",
    "A26": "English Opening, Closed System",
    "A27": "English Opening, Three Knights System",
    "A28": "English Opening, Four Knights System",
    "A29": "English Opening, Four Knights, Kingside Fianchetto",
    "A30": "English Opening, Symmetrical Variation",
    "A31": "English Opening, Symmetrical, Benoni Formation",
    "A32": "English Opening, Symmetrical, 1...c5 2.Nf3 Nf6 3.d4",
    "A33": "English Opening, Symmetrical, 1...c5 2.Nf3 Nf6 3.c4",
    "A34": "English Opening, Symmetrical, Three Knights",
    "A35": "English Opening, Symmetrical, Four Knights",
    "A36": "English Opening, Symmetrical, Botvinnik System",
    "A37": "English Opening, Symmetrical, Botvinnik System Reversed",
    "A38": "English Opening, Symmetrical, Main Line with d3",
    "A39": "English Opening, Symmetrical, Main Line with d4",
    "A40": "Queen's Pawn Opening (including various 1.d4 openings)",
    "A41": "Queen's Pawn Opening (1.d4 with various Black defenses)",
    "A42": "Modern Defense, Averbakh System",
    "A43": "Old Benoni Defense",
    "A44": "Old Benoni Defense, Czech Variation",
    "A45": "Queen's Pawn Game",
    "A46": "Queen's Pawn Game, Torre Attack",
    "A47": "Queen's Indian Defense",
    "A48": "King's Indian, East Indian Defense",
    "A49": "King's Indian, Fianchetto without c4",
    "A50": "Queen's Pawn Game, Black Knights' Tango",
    "A51": "Budapest Gambit Declined",
    "A52": "Budapest Gambit, Accepted",
    "A53": "Old Indian Defense",
    "A54": "Old Indian, Ukrainian Variation",
    "A55": "Old Indian, Main Line",
    "A56": "Benoni Defense",
    "A57": "Benko Gambit",
    "A58": "Benko Gambit Accepted, Fully",
    "A59": "Benko Gambit, 7.e4",
    "A60": "Benoni Defense, Modern Variation",
    "A61": "Benoni, Uhlmann Variation",
    "A62": "Benoni, Fianchetto Variation",
    "A63": "Benoni, Fianchetto Variation, 9...Nbd7",
    "A64": "Benoni, Fianchetto Variation, 11...Re8",
    "A65": "Benoni, 6.e4",
    "A66": "Benoni, Pawn Storm Variation",
    "A67": "Benoni, Taimanov Variation",
    "A68": "Benoni, Four Pawns Attack",
    "A69": "Benoni, Four Pawns Attack, Main Line",
    "A70": "Benoni, Classical with 7.Nf3",
    "A71": "Benoni, Classical, 8.Bg5",
    "A72": "Benoni, Classical with 9.O-O",
    "A73": "Benoni, Classical, 9.O-O, Main Line",
    "A74": "Benoni, Classical, 9...a6, 10.a4",
    "A75": "Benoni, Classical with ...a6 and 10...Bg4",
    "A76": "Benoni, Classical, 9...Re8",
    "A77": "Benoni, Classical, 9...Re8, 10.Nd2",
    "A78": "Benoni, Classical with ...Re8 and ...Na6",
    "A79": "Benoni, Classical, 11.f3",
    "A80": "Dutch Defense",
    "A81": "Dutch, Blackmar's First Gambit",
    "A82": "Dutch, Staunton Gambit",
    "A83": "Dutch, Staunton Gambit, Staunton's Line",
    "A84": "Dutch, Rubinstein Variation",
    "A85": "Dutch, Queen's Knight Variation",
    "A86": "Dutch, Leningrad Variation",
    "A87": "Dutch, Leningrad, Main Line",
    "A88": "Dutch, Leningrad, Main Line with 7...c6",
    "A89": "Dutch, Leningrad, Main Line with Nc6",
    "A90": "Dutch, Stonewall",
    "A91": "Dutch, Stonewall, 8.a4",
    "A92": "Dutch, Stonewall with Nc3",
    "A93": "Dutch, Stonewall, Botvinnik Variation",
    "A94": "Dutch, Stonewall with Ba3",
    "A95": "Dutch, Stonewall with Nc3",
    "A96": "Dutch, Classical Variation",
    "A97": "Dutch, Ilyin-Genevsky Variation",
    "A98": "Dutch, Ilyin-Genevsky Variation with Qc2",
    "A99": "Dutch, Ilyin-Genevsky Variation with b3",

    // B-series: Semi-Open Games (except French Defense)
    "B00": "Uncommon King's Pawn Opening",
    "B01": "Scandinavian Defense",
    "B02": "Alekhine's Defense",
    "B03": "Alekhine's Defense, 4.Nf3",
    "B04": "Alekhine's Defense, Modern Variation",
    "B05": "Alekhine's Defense, Modern Variation, Main Line",
    "B06": "Robatsch (Modern) Defense",
    "B07": "Pirc Defense",
    "B08": "Pirc, Classical (Two Knights) System",
    "B09": "Pirc, Austrian Attack",
    "B10": "Caro-Kann Defense",
    "B11": "Caro-Kann, Two Knights, 3...Bg4",
    "B12": "Caro-Kann Defense",
    "B13": "Caro-Kann, Exchange Variation",
    "B14": "Caro-Kann, Panov-Botvinnik Attack",
    "B15": "Caro-Kann, Tartakower (Nimzovich) Variation",
    "B16": "Caro-Kann, Bronstein-Larsen Variation",
    "B17": "Caro-Kann, Steinitz Variation",
    "B18": "Caro-Kann, Classical Variation",
    "B19": "Caro-Kann, Classical, 7...Nd7",
    "B20": "Sicilian Defense",
    "B21": "Sicilian, Grand Prix Attack",
    "B22": "Sicilian, Alapin Variation (2.c3)",
    "B23": "Sicilian, Closed",
    "B24": "Sicilian, Closed",
    "B25": "Sicilian, Closed",
    "B26": "Sicilian, Closed, 6.Be3",
    "B27": "Sicilian Defense, Various",
    "B28": "Sicilian, O'Kelly Variation",
    "B29": "Sicilian, Nimzovich-Rubinstein Variation",
    "B30": "Sicilian Defense, Old Sicilian",
    "B31": "Sicilian, Nimzovich-Rossolimo Attack (with ...g6, without ...d6)",
    "B32": "Sicilian Defense",
    "B33": "Sicilian, Pelikan (Lasker/Sveshnikov) Variation",
    "B34": "Sicilian, Accelerated Fianchetto",
    "B35": "Sicilian, Accelerated Fianchetto, Modern Variation with Bc4",
    "B36": "Sicilian, Accelerated Fianchetto, Maroczy Bind",
    "B37": "Sicilian, Accelerated Fianchetto, Maroczy Bind, 5...Bg7",
    "B38": "Sicilian, Accelerated Fianchetto, Maroczy Bind, 6.Be3",
    "B39": "Sicilian, Accelerated Fianchetto, Breyer Variation",
    "B40": "Sicilian Defense",
    "B41": "Sicilian, Kan Variation",
    "B42": "Sicilian, Kan, 5.Bd3",
    "B43": "Sicilian, Kan, 5.Nc3",
    "B44": "Sicilian, Szen Variation, Hedgehog Variation",
    "B45": "Sicilian, Taimanov Variation",
    "B46": "Sicilian, Taimanov Variation",
    "B47": "Sicilian, Taimanov (Bastrikov) Variation",
    "B48": "Sicilian, Taimanov Variation",
    "B49": "Sicilian, Taimanov Variation",
    "B50": "Sicilian",
    "B51": "Sicilian, Canal-Sokolsky (Rossolimo) Attack",
    "B52": "Sicilian, Canal-Sokolsky Attack, 3...Bd7",
    "B53": "Sicilian, Chekhover Variation",
    "B54": "Sicilian",
    "B55": "Sicilian, Prins Variation, Venice Attack",
    "B56": "Sicilian",
    "B57": "Sicilian, Sozin (not Scheveningen)",
    "B58": "Sicilian, Classical",
    "B59": "Sicilian, Boleslavsky Variation, 7.Nb3",
    "B60": "Sicilian, Richter-Rauzer",
    "B61": "Sicilian, Richter-Rauzer, Larsen Variation, 7.Qd2",
    "B62": "Sicilian, Richter-Rauzer, 6...e6",
    "B63": "Sicilian, Richter-Rauzer Attack",
    "B64": "Sicilian, Richter-Rauzer Attack",
    "B65": "Sicilian, Richter-Rauzer Attack, 7...Be7 Defense, 9.f4",
    "B66": "Sicilian, Richter-Rauzer Attack, 7...a6",
    "B67": "Sicilian, Richter-Rauzer Attack, 7...a6 Defense, 8...Bd7",
    "B68": "Sicilian, Richter-Rauzer Attack, 7...a6 Defense, 9...Be7",
    "B69": "Sicilian, Richter-Rauzer Attack, 7...a6 Defense, 11.Bxf6",
    "B70": "Sicilian, Dragon Variation",
    "B71": "Sicilian, Dragon, Levenfish Variation",
    "B72": "Sicilian, Dragon, 6.Be3",
    "B73": "Sicilian, Dragon, Classical, 8.O-O",
    "B74": "Sicilian, Dragon, Classical, 9.Nb3",
    "B75": "Sicilian, Dragon, Yugoslav Attack",
    "B76": "Sicilian, Dragon, Yugoslav Attack, 7...O-O",
    "B77": "Sicilian, Dragon, Yugoslav Attack, 9.Bc4",
    "B78": "Sicilian, Dragon, Yugoslav Attack, 10.O-O-O",
    "B79": "Sicilian, Dragon, Yugoslav Attack, 12.h4",
    "B80": "Sicilian, Scheveningen",
    "B81": "Sicilian, Scheveningen, Keres Attack",
    "B82": "Sicilian, Scheveningen, 6.f4",
    "B83": "Sicilian, Scheveningen, 6.Be2",
    "B84": "Sicilian, Scheveningen, Classical Variation",
    "B85": "Sicilian, Scheveningen, Classical Variation with ...Qc7 and ...Nc6",
    "B86": "Sicilian, Sozin Attack",
    "B87": "Sicilian, Sozin with ...a6 and ...b5",
    "B88": "Sicilian, Sozin, Leonhardt Variation",
    "B89": "Sicilian, Sozin, Main Line",
    "B90": "Sicilian, Najdorf",
    "B91": "Sicilian, Najdorf, Zagreb (Fianchetto) Variation",
    "B92": "Sicilian, Najdorf, Zagreb Variation",
    "B93": "Sicilian, Najdorf, 6.f4",
    "B94": "Sicilian, Najdorf, 6.Bg5",
    "B95": "Sicilian, Najdorf, 6...e6 7.f4",
    "B96": "Sicilian, Najdorf, 7.f4",
    "B97": "Sicilian, Najdorf, 7...Qb6",
    "B98": "Sicilian, Najdorf, 7...Be7",
    "B99": "Sicilian, Najdorf, 7...Be7 Main Line",

    // C-series: Open Games and Queen's Pawn Games
    "C00": "French Defense",
    "C01": "French, Exchange Variation",
    "C02": "French, Advance Variation",
    "C03": "French, Tarrasch",
    "C04": "French, Tarrasch, Guimard Main Line",
    "C05": "French, Tarrasch, Closed Variation",
    "C06": "French, Tarrasch, Closed Variation, Main Line",
    "C07": "French, Tarrasch, Open Variation",
    "C08": "French, Tarrasch, Open, 4.exd5 exd5",
    "C09": "French, Tarrasch, Open Variation, Main Line",
    "C10": "French, Paulsen Variation",
    "C11": "French, Classical",
    "C12": "French, MacCutcheon Variation",
    "C13": "French, Classical, Anderssen Variation",
    "C14": "French, Classical, Steinitz Variation",
    "C15": "French, Winawer Variation",
    "C16": "French, Winawer, Advance Variation",
    "C17": "French, Winawer, Advance Variation",
    "C18": "French, Winawer, Advance Variation",
    "C19": "French, Winawer, Advance, 6...Ne7",
    "C20": "King's Pawn Game",
    "C21": "Center Game",
    "C22": "Center Game, Paulsen Attack",
    "C23": "Bishop's Opening",
    "C24": "Bishop's Opening, Berlin Defense",
    "C25": "Vienna Game",
    "C26": "Vienna, Falkbeer Variation",
    "C27": "Vienna Game",
    "C28": "Vienna Game",
    "C29": "Vienna Gambit",
    "C30": "King's Gambit",
    "C31": "King's Gambit Declined, Falkbeer Counter-Gambit",
    "C32": "King's Gambit Declined, Falkbeer Counter-Gambit",
    "C33": "King's Gambit Accepted",
    "C34": "King's Gambit Accepted",
    "C35": "King's Gambit Accepted, Cunningham Defense",
    "C36": "King's Gambit Accepted, Abbazia Defense",
    "C37": "King's Gambit Accepted, Quaade Gambit",
    "C38": "King's Gambit Accepted, Traditional Variation",
    "C39": "King's Gambit Accepted, Kieseritzky Gambit",
    "C40": "King's Knight Opening",
    "C41": "Philidor Defense",
    "C42": "Petrov's Defense",
    "C43": "Petrov, Modern Attack",
    "C44": "King's Pawn Game",
    "C45": "Scotch Game",
    "C46": "Three Knights Opening",
    "C47": "Four Knights, Scotch Variation",
    "C48": "Four Knights, Spanish Variation",
    "C49": "Four Knights, Double Ruy Lopez",
    "C50": "Giuoco Piano",
    "C51": "Evans Gambit",
    "C52": "Evans Gambit",
    "C53": "Giuoco Piano",
    "C54": "Giuoco Piano",
    "C55": "Two Knights Defense",
    "C56": "Two Knights Defense",
    "C57": "Two Knights Defense",
    "C58": "Two Knights Defense, Morphy Variation",
    "C59": "Two Knights Defense, Morphy Variation, Polerio Def. Bogoljubow Var.",
    "C60": "Ruy Lopez (Spanish Opening)",
    "C61": "Ruy Lopez, Bird's Defense",
    "C62": "Ruy Lopez, Old Steinitz Defense",
    "C63": "Ruy Lopez, Schliemann Defense",
    "C64": "Ruy Lopez, Classical Defense",
    "C65": "Ruy Lopez, Berlin Defense",
    "C66": "Ruy Lopez, Berlin Defense, Closed Bernstein Variation",
    "C67": "Ruy Lopez, Berlin Defense, Open Variation",
    "C68": "Ruy Lopez, Exchange Variation",
    "C69": "Ruy Lopez, Exchange, Gligoric Variation",
    "C70": "Ruy Lopez",
    "C71": "Ruy Lopez, Modern Steinitz Defense",
    "C72": "Ruy Lopez, Modern Steinitz Defense, 5.O-O",
    "C73": "Ruy Lopez, Modern Steinitz Defense",
    "C74": "Ruy Lopez, Modern Steinitz Defense",
    "C75": "Ruy Lopez, Modern Steinitz Defense",
    "C76": "Ruy Lopez, Modern Steinitz Defense, Fianchetto Variation",
    "C77": "Ruy Lopez, Morphy Defense",
    "C78": "Ruy Lopez, 5.O-O",
    "C79": "Ruy Lopez, Steinitz Defense Deferred",
    "C80": "Ruy Lopez, Open",
    "C81": "Ruy Lopez, Open, Howell Attack",
    "C82": "Ruy Lopez, Open, 9.c3",
    "C83": "Ruy Lopez, Open, Classical Defense",
    "C84": "Ruy Lopez, Closed",
    "C85": "Ruy Lopez, Exchange Variation Doubly Deferred",
    "C86": "Ruy Lopez, Worrall Attack",
    "C87": "Ruy Lopez, Closed, Averbach Variation",
    "C88": "Ruy Lopez, Closed",
    "C89": "Ruy Lopez, Marshall Counterattack",
    "C90": "Ruy Lopez, Closed",
    "C91": "Ruy Lopez, Closed, 9.d4",
    "C92": "Ruy Lopez, Closed, 9.d4 d6 10.c3 Bd7",
    "C93": "Ruy Lopez, Closed, Smyslov Defense",
    "C94": "Ruy Lopez, Closed, Breyer Defense",
    "C95": "Ruy Lopez, Closed, Breyer, 10.d4",
    "C96": "Ruy Lopez, Closed, 10.c3",
    "C97": "Ruy Lopez, Closed, Chigorin Defense",
    "C98": "Ruy Lopez, Closed, Chigorin, 12...Nc6",
    "C99": "Ruy Lopez, Closed, Chigorin, 12...c5d4",

    // D-series: Closed Games and Indian Defenses
    "D00": "Queen's Pawn Game, Mason Variation",
    "D01": "Richter-Veresov Attack",
    "D02": "Queen's Pawn Game, 2.Nf3",
    "D03": "Torre Attack (Tartakower Variation)",
    "D04": "Queen's Pawn Game, Colle System",
    "D05": "Queen's Pawn Game, Colle System (Zukertort Variation)",
    "D06": "Queen's Gambit Declined",
    "D07": "Queen's Gambit Declined, Chigorin Defense",
    "D08": "Queen's Gambit Declined, Albin Counter Gambit",
    "D09": "Queen's Gambit Declined, Albin Counter Gambit, 5.g3",
    "D10": "Queen's Gambit Declined Slav Defense",
    "D11": "Queen's Gambit Declined Slav Defense, 3.Nf3",
    "D12": "Queen's Gambit Declined Slav Defense, 4.e3 Bf5",
    "D13": "Queen's Gambit Declined Slav Defense, Exchange Variation",
    "D14": "Queen's Gambit Declined Slav Defense, Exchange Variation",
    "D15": "Queen's Gambit Declined Slav Defense, 4.Nc3",
    "D16": "Queen's Gambit Declined Slav Defense, Alekhine Variation",
    "D17": "Queen's Gambit Declined Slav Defense, Czech Defense",
    "D18": "Queen's Gambit Declined Slav Defense, Dutch Variation",
    "D19": "Queen's Gambit Declined Slav Defense, Dutch Variation",
    "D20": "Queen's Gambit Accepted",
    "D21": "Queen's Gambit Accepted, 3.Nf3",
    "D22": "Queen's Gambit Accepted, Alekhine Defense",
    "D23": "Queen's Gambit Accepted, Alekhine Defense",
    "D24": "Queen's Gambit Accepted, 4.Nc3",
    "D25": "Queen's Gambit Accepted, 4.e3",
    "D26": "Queen's Gambit Accepted, Classical Variation",
    "D27": "Queen's Gambit Accepted, Classical Variation",
    "D28": "Queen's Gambit Accepted, Classical Variation",
    "D29": "Queen's Gambit Accepted, Classical Variation",
    "D30": "Queen's Gambit Declined",
    "D31": "Queen's Gambit Declined, Queen's Knight Variation",
    "D32": "Queen's Gambit Declined, Tarrasch Defense",
    "D33": "Queen's Gambit Declined, Tarrasch Defense, Schlechter Variation",
    "D34": "Queen's Gambit Declined, Tarrasch Defense, 7.Qb3",
    "D35": "Queen's Gambit Declined, Exchange Variation",
    "D36": "Queen's Gambit Declined, Exchange Variation, 6.Qc2 (Reshevsky Variation)",
    "D37": "Queen's Gambit Declined, 4.Nf3",
    "D38": "Queen's Gambit Declined, Ragozin Variation",
    "D39": "Queen's Gambit Declined, Ragozin, Vienna Variation",
    "D40": "Queen's Gambit Declined, Semi-Tarrasch Defense",
    "D41": "Queen's Gambit Declined, Semi-Tarrasch, 5.cd",
    "D42": "Queen's Gambit Declined, Semi-Tarrasch, 7.Bd3",
    "D43": "Queen's Gambit Declined, Semi-Slav",
    "D44": "Queen's Gambit Declined, Semi-Slav, 5.Bg5 dc",
    "D45": "Queen's Gambit Declined, Semi-Slav, 5.e3",
    "D46": "Queen's Gambit Declined, Semi-Slav, 6.Bd3",
    "D47": "Queen's Gambit Declined, Semi-Slav, 7.Bc4",
    "D48": "Queen's Gambit Declined, Semi-Slav, Meran",
    "D49": "Queen's Gambit Declined, Semi-Slav, Meran",
    "D50": "Queen's Gambit Declined, 4.Bg5",
    "D51": "Queen's Gambit Declined, 4.Bg5 Nbd7",
    "D52": "Queen's Gambit Declined, Cambridge Springs Variation",
    "D53": "Queen's Gambit Declined, 4.Bg5 Be7",
    "D54": "Queen's Gambit Declined, Anti-Neo-Orthodox Variation",
    "D55": "Queen's Gambit Declined, 6.Nf3",
    "D56": "Queen's Gambit Declined, Lasker Defense",
    "D57": "Queen's Gambit Declined, Lasker Defense, Main Line",
    "D58": "Queen's Gambit Declined, Tartakower System",
    "D59": "Queen's Gambit Declined, Tartakower System, 8.cd Nxd5",
    "D60": "Queen's Gambit Declined, Orthodox Defense",
    "D61": "Queen's Gambit Declined, Orthodox Defense, Rubinstein Variation",
    "D62": "Queen's Gambit Declined, Orthodox Defense, 7.Qc2 c5, 8.cd (Rubinstein)",
    "D63": "Queen's Gambit Declined, Orthodox Defense, 7.Rc1",
    "D64": "Queen's Gambit Declined, Orthodox Defense, Rubinstein Attack",
    "D65": "Queen's Gambit Declined, Orthodox Defense, Rubinstein Attack, Main Line",
    "D66": "Queen's Gambit Declined, Orthodox Defense, Bd3 Line",
    "D67": "Queen's Gambit Declined, Orthodox Defense, Bd3 Line, Capablanca Freeing Maneuver",
    "D68": "Queen's Gambit Declined, Orthodox Defense, Classical Variation",
    "D69": "Queen's Gambit Declined, Orthodox Defense, Classical Variation, 13.de",
    "D70": "Neo-Grünfeld Defense",
    "D71": "Neo-Grünfeld, 5.cd",
    "D72": "Neo-Grünfeld, 5.cd, Main Line",
    "D73": "Neo-Grünfeld, 5.Nf3",
    "D74": "Neo-Grünfeld, Nxd5, 7.O-O Nb6",
    "D75": "Neo-Grünfeld, Nxd5, 7.O-O c5, 8.dc",
    "D76": "Neo-Grünfeld, Nxd5, 7.O-O Nb6",
    "D77": "Neo-Grünfeld, 6.O-O",
    "D78": "Neo-Grünfeld, 6.O-O c6",
    "D79": "Neo-Grünfeld, 6.O-O, Main Line",
    "D80": "Grünfeld Defense",
    "D81": "Grünfeld, Russian Variation",
    "D82": "Grünfeld, 4.Bf4",
    "D83": "Grünfeld, Grünfeld Gambit",
    "D84": "Grünfeld, Grünfeld Gambit Accepted",
    "D85": "Grünfeld, Exchange Variation",
    "D86": "Grünfeld, Exchange, Classical Variation",
    "D87": "Grünfeld, Exchange, Spassky Variation",
    "D88": "Grünfeld, Spassky Variation, Main Line, 10...cd, 11.cd",
    "D89": "Grünfeld, Spassky Variation, Main Line, 13.Bd3",
    "D90": "Grünfeld, Three Knights Variation",
    "D91": "Grünfeld, Three Knights Variation",
    "D92": "Grünfeld, 5.Bf4",
    "D93": "Grünfeld, with Bf4 & e3",
    "D94": "Grünfeld, 5.e3",
    "D95": "Grünfeld, with e3 & Qb3",
    "D96": "Grünfeld, Russian Variation",
    "D97": "Grünfeld, Russian Variation with e4",
    "D98": "Grünfeld, Russian, Smyslov Variation",
    "D99": "Grünfeld Defense, Smyslov, Main Line",

    // E-series: Indian Defenses
    "E00": "Queen's Pawn Game, Non-standard replies",
    "E01": "Catalan Opening",
    "E02": "Catalan Opening, Open Defense",
    "E03": "Catalan Opening, Open Defense",
    "E04": "Catalan Opening, Open Defense, 5.Nf3",
    "E05": "Catalan Opening, Open Defense, Classical Line",
    "E06": "Catalan Opening, Closed Defense, 5.Nf3",
    "E07": "Catalan Opening, Closed Defense, 6...Nbd7",
    "E08": "Catalan Opening, Closed Defense, 7.Qc2",
    "E09": "Catalan Opening, Closed Defense, Main Line",
    "E10": "Queen's Pawn Game, Blumenfeld Counter Gambit",
    "E11": "Bogo-Indian Defense",
    "E12": "Queen's Indian Defense",
    "E13": "Queen's Indian, 4.Nc3, Main Line",
    "E14": "Queen's Indian, 4.e3",
    "E15": "Queen's Indian, 4.g3",
    "E16": "Queen's Indian, Capablanca Variation",
    "E17": "Queen's Indian, 5.Bg2 Be7",
    "E18": "Queen's Indian, Old Main Line, 7.Nc3",
    "E19": "Queen's Indian, Old Main Line, 9.Qxc3",
    "E20": "Nimzo-Indian Defense",
    "E21": "Nimzo-Indian, Three Knights Variation",
    "E22": "Nimzo-Indian, Spielmann Variation",
    "E23": "Nimzo-Indian, Spielmann, 4...c5, 5.dc Nc6",
    "E24": "Nimzo-Indian, Sämisch Variation",
    "E25": "Nimzo-Indian, Sämisch, Keres Variation",
    "E26": "Nimzo-Indian, Sämisch, 4...O-O 5.a3",
    "E27": "Nimzo-Indian, Sämisch Variation, 5...Nc6",
    "E28": "Nimzo-Indian, Sämisch Variation",
    "E29": "Nimzo-Indian, Sämisch, Main Line",
    "E30": "Nimzo-Indian, Leningrad Variation",
    "E31": "Nimzo-Indian, Leningrad, Main Line",
    "E32": "Nimzo-Indian, Classical Variation",
    "E33": "Nimzo-Indian, Classical, 4...Nc6",
    "E34": "Nimzo-Indian, Classical, Noa Variation",
    "E35": "Nimzo-Indian, Classical, Noa Variation, 5.cd ed",
    "E36": "Nimzo-Indian, Classical, Noa Variation, 5.a3",
    "E37": "Nimzo-Indian, Classical, Noa Variation, Main Line",
    "E38": "Nimzo-Indian, Classical, 4...c5",
    "E39": "Nimzo-Indian, Classical, Pirc Variation",
    "E40": "Nimzo-Indian, 4.e3",
    "E41": "Nimzo-Indian, 4.e3 c5",
    "E42": "Nimzo-Indian, 4.e3 c5, 5.Ne2 (Rubinstein)",
    "E43": "Nimzo-Indian, Fischer Variation",
    "E44": "Nimzo-Indian, Fischer Variation, 5.Ne2",
    "E45": "Nimzo-Indian, 4.e3, Bronstein (Byrne) Variation",
    "E46": "Nimzo-Indian, 4.e3 O-O",
    "E47": "Nimzo-Indian, 4.e3 O-O, 5.Bd3",
    "E48": "Nimzo-Indian, 4.e3 O-O, 5.Bd3 d5",
    "E49": "Nimzo-Indian, 4.e3, Botvinnik System",
    "E50": "Nimzo-Indian, 4.e3 e8g8, 5.Nf3, without ...d5",
    "E51": "Nimzo-Indian, 4.e3 e8g8, 5.Nf3 d7d5",
    "E52": "Nimzo-Indian, 4.e3, Main Line with ...b6",
    "E53": "Nimzo-Indian, 4.e3, Main Line with ...c5",
    "E54": "Nimzo-Indian, 4.e3, Gligoric System with 7...dc",
    "E55": "Nimzo-Indian, 4.e3, Gligoric System, Bronstein Variation",
    "E56": "Nimzo-Indian, 4.e3, Main Line with 7...Nc6",
    "E57": "Nimzo-Indian, 4.e3, Main Line with 8...dc and 9...cd",
    "E58": "Nimzo-Indian, 4.e3, Main Line with 8...Bxc3",
    "E59": "Nimzo-Indian, 4.e3, Main Line",
    "E60": "King's Indian Defense",
    "E61": "King's Indian Defense, 3.Nc3",
    "E62": "King's Indian, Fianchetto Variation",
    "E63": "King's Indian, Fianchetto, Panno Variation",
    "E64": "King's Indian, Fianchetto, Yugoslav System",
    "E65": "King's Indian, Yugoslav, 7.O-O",
    "E66": "King's Indian, Fianchetto, Yugoslav Panno",
    "E67": "King's Indian, Fianchetto with ...Nd7",
    "E68": "King's Indian, Fianchetto, Classical Variation, 8.e4",
    "E69": "King's Indian, Fianchetto, Classical Main Line",
    "E70": "King's Indian, 4.e4",
    "E71": "King's Indian, Makagonov Variation (5.h3)",
    "E72": "King's Indian, 4.e4 d6 5.g3",
    "E73": "King's Indian, 5.Be2",
    "E74": "King's Indian, Averbakh, 6...c5",
    "E75": "King's Indian, Averbakh, Main Line",
    "E76": "King's Indian, Four Pawns Attack",
    "E77": "King's Indian, Four Pawns Attack, 6.Be2",
    "E78": "King's Indian, Four Pawns Attack, with Be2 and Nf3",
    "E79": "King's Indian, Four Pawns Attack, Main Line",
    "E80": "King's Indian, Sämisch Variation",
    "E81": "King's Indian, Sämisch, 5...O-O",
    "E82": "King's Indian, Sämisch, double Fianchetto Variation",
    "E83": "King's Indian, Sämisch, 6...Nc6",
    "E84": "King's Indian, Sämisch, Panno Main Line",
    "E85": "King's Indian, Sämisch, Orthodox Variation",
    "E86": "King's Indian, Sämisch, Orthodox, 7.Nge2 c6",
    "E87": "King's Indian, Sämisch, Orthodox, 7.d5",
    "E88": "King's Indian, Sämisch, Orthodox, 7.d5 c6",
    "E89": "King's Indian, Sämisch, Orthodox Main Line",
    "E90": "King's Indian, 5.Nf3",
    "E91": "King's Indian, 6.Be2",
    "E92": "King's Indian, Classical Variation",
    "E93": "King's Indian, Petrosian Variation",
    "E94": "King's Indian, Orthodox Variation",
    "E95": "King's Indian, Orthodox, 7...Nbd7, 8.Re1",
    "E96": "King's Indian, Orthodox, 7...Nbd7, Main Line",
    "E97": "King's Indian, Orthodox, Aronin-Taimanov Variation (Yugoslav Attack)",
    "E98": "King's Indian, Orthodox, Aronin-Taimanov, 9.Ne1",
    "E99": "King's Indian, Orthodox, Aronin-Taimanov, Main Line"
};

/**
 * Get a description for an ECO code
 * 
 * @param {string} ecoCode - The ECO code to look up (e.g., "A45")
 * @returns {string} - Description of the opening or "Unknown opening" if not found
 */
function getEcoDescription(ecoCode) {
    if (!ecoCode) return "Unknown opening";
    
    // Standardize input (uppercase and trim)
    const standardCode = ecoCode.toString().trim().toUpperCase();
    
    // Return the description if found, otherwise return unknown
    return ecoCodesLibrary[standardCode] || "Unknown opening";
}

/**
 * Initialize ECO code tooltips on a page
 * 
 * @param {string} selector - CSS selector for elements with ECO codes
 */
function initializeEcoTooltips(selector = '.eco-code') {
    document.querySelectorAll(selector).forEach(element => {
        const ecoCode = element.textContent.trim();
        const description = getEcoDescription(ecoCode);
        
        // Set tooltip attributes
        element.setAttribute('title', description);
        element.setAttribute('data-bs-toggle', 'tooltip');
        element.setAttribute('data-bs-placement', 'top');
        
        // Add hover effect class
        element.classList.add('eco-code-tooltip');
    });
    
    // Initialize Bootstrap tooltips
    if (typeof bootstrap !== 'undefined' && bootstrap.Tooltip) {
        const tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
        tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl);
        });
    }
}

// Export functions if in a module environment
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        getEcoDescription,
        initializeEcoTooltips
    };
}